version: '3'
services:
    nginx:
            image: nginx:latest
            container_name: nginx
            #volumes:
            #        - ./nginx.conf:/etc/nginx/nginx.conf
            ports:
                    - "80:80"
                    - "443:443"
            networks:
                    - app-network
            depends_on:
                    - hello1

    hello1:
            image: run_app
            container_name: run_app
            expose:
                    - "2000"
            ports:
                    - "2000:2000"
            networks:
                    - app-network

networks:
    app-network:
