version: '3'
services:
    nginx:
            image: nginx:1.27.1
            container_name: nginx
            volumes:
                    - ./site_conf:/etc/nginx/conf.d/adooba.conf
            ports:
                    - "80:80"
                    - "8080:80"
                    - "2100:2100"
                    - "443:443"
            networks:
                    - app-network
            depends_on:
                    - hello1

    hello1:
            image: run_app
            container_name: run_app
            expose:
                    - "2000"
            ports:
                    - "2000:2000"
            networks:
                    - app-network

networks:
    app-network:
